/* Interaction, sound, RSVP and sharing features for the invitation. */
document.addEventListener('DOMContentLoaded',()=>{
  const envelope=$('#envelope'), seal=$('#seal'); let opened=false;
  const openEnvelope=()=>{if(opened)return;opened=true; envelope.classList.add('opened'); $('.tap-hint').style.opacity='0'; startMusic(); setTimeout(()=>{ $('#experience').classList.add('hidden'); $('#invitation').classList.remove('hidden'); $('#invitation').focus({preventScroll:true}); window.scrollTo({top:0,behavior:'smooth'}); if(window.gsap)gsap.from('.invitation-card',{scale:.86,opacity:0,duration:1.5,ease:'power3.out'}); },1650);};
  seal.addEventListener('click',openEnvelope); envelope.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')openEnvelope()});
  setInterval(updateCountdown,1000);updateCountdown(); $('#rsvpButton').onclick=()=>{ $('#rsvpForm [name=name]').value=nameFromQuery()||''; $('#rsvpModal').showModal()}; $('.close-modal').onclick=()=>$('#rsvpModal').close();
  $('#rsvpForm').onsubmit=e=>{e.preventDefault(); $('.form-message').textContent='شكرًا لتأكيدكم. نتطلع لرؤيتكم بكل حب.'; e.target.querySelector('button').disabled=true;};
  $('#shareButton').onclick=async()=>{const data={title:wedding.title,text:wedding.description,url:location.href};try{if(navigator.share)await navigator.share(data);else await copyLink();}catch(e){}};
  $('#copyButton').onclick=copyLink; $('#calendarButton').onclick=downloadCalendar; $('#soundToggle').onclick=toggleMusic;
});
function updateCountdown(){const d=new Date(wedding.date)-Date.now();const set=(id,n)=>$(id).textContent=String(Math.max(0,n)).padStart(2,'0');set('#days',Math.floor(d/864e5));set('#hours',Math.floor(d/36e5)%24);set('#minutes',Math.floor(d/6e4)%60);set('#seconds',Math.floor(d/1e3)%60)}
async function copyLink(){try{await navigator.clipboard.writeText(location.href);$('#copyButton').textContent='تم نسخ الرابط ✓';setTimeout(()=>$('#copyButton').textContent='نسخ رابط الدعوة',2000)}catch(e){prompt('انسخ الرابط:',location.href)}}
function downloadCalendar(){const start=wedding.date.replace(/[-:]/g,'').replace('.000','').replace('+02:00','');const text=`BEGIN:VCALENDAR\nVERSION:2.0\nBEGIN:VEVENT\nDTSTART:${start}\nSUMMARY:${wedding.title}\nLOCATION:${wedding.venue}\nDESCRIPTION:${wedding.description}\nEND:VEVENT\nEND:VCALENDAR`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/calendar'}));a.download='wedding-invitation.ics';a.click();URL.revokeObjectURL(a.href)}
/* The recitation is an ordinary HTML audio element for reliable mobile playback. */
let recitation,isPlaying=false;function startMusic(){if(!recitation){recitation=new Audio(wedding.music);recitation.preload='metadata';recitation.volume=Number($('#volume').value);recitation.addEventListener('ended',()=>{isPlaying=false;$('#soundToggle').classList.remove('playing');$('#soundToggle').setAttribute('aria-label','تشغيل التلاوة')})}recitation.play().then(()=>{isPlaying=true;$('#soundToggle').classList.add('playing');$('#soundToggle').setAttribute('aria-label','إيقاف التلاوة')}).catch(()=>{})}function toggleMusic(){if(!recitation||recitation.paused){startMusic();return}recitation.pause();isPlaying=false;$('#soundToggle').classList.remove('playing');$('#soundToggle').setAttribute('aria-label','تشغيل التلاوة')}
